# Generated by Django 4.1 on 2024-03-11 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('task_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_details', to='tasks.taskdetails')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringTaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('repeat_interval', models.DurationField(default=datetime.timedelta(days=1))),
                ('times_finished', models.IntegerField(default=0)),
                ('task_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskdetails')),
            ],
        ),
    ]
